### PR TITLE
Added static file handling to restup

### PR DESCRIPTION
**Pull request by Jark**
Hi,

I've done a bit of hobbying and I managed to add static file handling to restup in quite a nice way I think.

The major things I did:
- split out the rest related stuff from HttpServer and moved it into RestRouteHandler
- made it so that you can add multiple "route handlers" that are mapped to a prefix.
- moved the MediaType enum out of HttpMessage into rest land since it seems that the logic that was using it would be very rest specific
- I've updated the HeadedDemo with a WebView and some samplefiles so we can see what the output would be in a webbrowser (try browsing to / or /index.html from within the sample app), both the HeadedDemo and HeadlessDemo now serve the files from the DemoStaticFiles project
- I've left a RestWebServer with the same interface so existing projects just using restup will not be affected

Some things I still need to do:
- add some doc to the README about the new routing stuff
- do the matching of api routes based on most specific, currently if you add the file handler on the root address and then add a rest handler on "/api" the rest handler never gets called
- add unit tests around the StaticFileHandler

I think I got a bit carried away here, but very much enjoyed the process of refactoring / building it, so feel free to refuse the pull request or request big changes. The big reason behind the route handler stuff is that I want to have a look into web-sockets after this :)

I plan on working on this some more tomorrow evening to add the missing things in that I mentioned above, but would appreciate some early feedback if possible.

Cheers,

Jark

### CODE REVIEW

**Comment by tomkuijsten** [comment]
Thanks for the pull request!

I just got another pull request (#33) with the same functionality. I'll review both request and pick the one most appropriate for this project.

**Comment by tomkuijsten** [comment]
I was thinking about implementing this somehow, but I was not quit sure how to merge it with the REST controllers without confusing developers on how to use it. This look promising!

**Comment by tomkuijsten** [comment]
About the readme, I want to create some wiki pages with different scenario's. It's getting a bit too big for one readme.

**Comment by Jark** [comment]
I've solved the todo items, feel free to merge it back in now.

**Pull request merged**
