### PR TITLE
Support controllers in windows runtime components

### PR DESCRIPTION
**Pull request by Jark**
Fixes issue  #45.

I ended up just having to put the following interfaces into a separate Windows Runtime Component.
- IRestResponse
- IContentRestResponse
- IGetResponse
- IPutResponse
- IPostResponse
- IDeleteResponse

I've also added the ability to return IAsyncOperation<T> as that's the only async related return value that's allowed in Windows Runtime Components.

@tomkuijsten would be grateful if you could have a look over the code and let me know if you want me to modify anything. Apart from adding references there should be no breaking changes with existing code.

### CODE REVIEW

**Comment by tomkuijsten** [comment]
I have some time tonight, I'll take a look.

**Comment by tomkuijsten** [comment]
Code looks fine, no functional changes as far as I can see.

On question though, did you change the namespace in that new project on purpose? It's missing the "Devkoes" prefix, which all other projects do have.

**Comment by tomkuijsten** [comment]
And do you have some msdn article which explains the problem when using unsealed classes in UWP apps? I'd like to read a bit more about it and it would be handy to have a link in the history of the issue.

**Comment by Jark** [comment]
Fixed the naming issue, must've forgotten in my once-to-many recreation of the new project :)

Here's the article I referred to for windows runtime component limitations, first paragraph has most of the limitations: https://msdn.microsoft.com/en-gb/library/br230301.aspx

Can you just double check that last commit, and if that's fine with you then we can merge it back in :)

**Pull request merged**
