### PR TITLE
Serialize and deserialize with the correct encoding, fixes #119

### LINKED ISSUE #119: Serialize xml:  XML declaration returns utf-16 versus utf-8
I send a get request from my client with the Accept-Charset = UTF-8, but the xml declaration encoding attribute is set to UTF-16.

Here is what my response body xml looks like:

\<?xml version="1.0" encoding="utf-16" ?>
<picture xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"xmlns:xsd="http://www.w3.org/2001/XMLSchema"filename="test.jpg">...</picture>"

Here is the object that is being serialized in .net:

    [XmlRoot(ElementName ="picture", Namespace = "")]
    public sealed class picture
    {
        [XmlAttribute(AttributeName = "filename")]
        public string filename { get; set; }
        [XmlText]
        public String ImageBytesBase64String { get; set; }
    }

How do I get the xml root node encoding attribute set to "utf-8"?

### PR DESCRIPTION
**Pull request by Jark**
This pull request makes sure that any xml documents returned inside the body will get the correct encoding embedded into them.

I've also added tests covering both the serializing and deserializing of xml with different encodings.

### CODE REVIEW

**Comment by Jark** [comment]
@tomkuijsten would you mind reviewing the code?

**Comment by tomkuijsten** [comment]
I have a look tomorrow, time is a bit limited now. Do you mind [refreshing the certificates](http://go.microsoft.com/fwlink/?LinkID=241478)? That's why the build is failing and no artifacts (nuget packages) are available.

**Comment by Jark** [comment]
Done, let's see if it works now.

**Comment by Jark** [comment]
Nope, apparently you have to create a certain type of certificate manually for it to work? I'll investigate further

**Comment by Jark** [comment]
Will have a look at lunch.

**Comment by tomkuijsten** [comment]
Looked at the code and ok with me to merge, just update the certificates for the green build and I'll do the merge.

**Comment by tomkuijsten** [comment]
You might want to update the version numbers (eg 1.0.1-beta1) in the .nuspec file, so we got a valid package name.

**Comment by tomkuijsten** [comment]
Got some time left, ill merge this and fix the others myself.

**Comment by Jark** [comment]
@tomkuijsten thanks, out of interest, how did you fix the certificate issue? Did disabling the native toolchain do it?

**Comment by tomkuijsten** [comment]
Nope, you have to create a new "test certificate" by opening the appxmanifest and don't use a password for it.

**Pull request merged**
