### PR TITLE
#47 Change protection on HttpServerResponse

### PR DESCRIPTION
**Pull request by HakanL**
Removed lock file from repo since it's generated

### CODE REVIEW

**Comment by tomkuijsten** [comment]
Thanks Hakan! Can you tell me why you changed the access modifier of  ```HttpServerResponse```?

**Comment by Jark** [comment]
@tomkuijsten I think it's related to https://github.com/tomkuijsten/restup/issues/47

**Comment by tomkuijsten** [comment]
My bad, I just read the comment of the PR, didn't see the link to #47.

**Comment by tomkuijsten** [comment]
As there is not much activity here and I don't really see the added value, I'll close this. Unless someone convinces me today to pull it anyway.

**Comment by HakanL** [comment]
Yea I think you can close this, I didn't realize there were public Create method since the internal class used the constructors instead of Create. So I don't think you need to change the protection (unless you want to make them private, would make more sense and use Create even inside your project).

**Comment by tomkuijsten** [comment]
Agree, fixed in 4ad804b890fc171c749a46b3b55ee0508c01341e

**Comment by HakanL** [comment]
Nice, thank you!

**Pull request closed without merging**
