### PR TITLE
Feature add support for cross origin headers

### LINKED ISSUE #77: Add an IHttpRequestFilterAttribute
I propose to add an IHttpRequestFilterAttribute which should allow you to reject certain calls or send a different request back. With this we could easily add CORS or authorisation support.

You should be able to apply this attribute on methods and on the class, the class one will be triggered first, and then the method level ones.

### PR DESCRIPTION
**Pull request by Jark**
Fixes #77 

@tomkuijsten mind having a look and seeing what you think? Haven't tested it after I added the ability to enable cors, but will give it another test tomorrow or on monday.

### CODE REVIEW

**Comment by tomkuijsten** [comment]
First of all, great work! Some quick remarks.

Did you hide the IHttpMessageInspector list intentionally in the HttpServer? I expected an AddMessageInspector method somewhere, but it's restricted to the EnableCors method now.

I'm missing a test case (in CorsSimpleRequests) for explicit origins (only * is tested now).

Couple of things we should document:
 - We don't check if any path is actually a REST endpoint
 - We always send back all REST verbs as accepted (although that might result in 400 bad request)
 - All requested headers are accepted
 - The max age header is set to 10 minutes

**Comment by tomkuijsten** [comment]
Might be better to introduce a CorsConfiguration object and accept that in EnableCors. To prevent a contract break if we want more control over the Cors configuration (accepted headers, timeout, etc)

**Comment by Jark** [comment]
I did hide the IHttpMessageInspector on purpose inside HttpServer so we can formalise the interface with the next change and then expose it when needed.

I've got a preflight request test that tests the explicit origin test (PreflightRequest_WithOnlyTheExactOriginEnabled_ReturnsTrue) but have added one for the simple request tests as well.

- I don't think we need to document: "We don't check if any path is actually a REST endpoint" & "We always send back all REST verbs as accepted (although that might result in 400 bad request)" since we set the cors on HttpServer level and not on the rest level

I've documented the other two points in the EnableCors method. 

I'll have a think about the EnableCors method, something fluenty could be a good solution as well.

**Comment by tomkuijsten** [comment]
With the documentation I ment  the wiki, not the code, should have been more clear about that.

You want it to be fluent to support more configuration options like:

```cs
server
  .EnableCors(new CorsConfiguration())
  .EnableAuthentication()
  .etc
```

?

I don't have that much experience with fluent api's, but that looks kinda neat (although I don't know how many other configuration we will add on server level).

**Comment by Jark** [comment]
I've added the fluent configuration to a separate branch: https://github.com/Jark/restup/commit/7c28fced0373ae6e99eeae61478985fe8cd8a3ef

See if you like it, basically the user would use it like this:

```c#
 httpServer.EnableCors(x => x
                     .AddAllowedOrigin("http://server1.com")
                     .AddAllowedOrigin("http://server2.com"));
```

or simply to allow all origins:

```c#
 httpServer.EnableCors();
```

we would then add more configuration options as needed to the ICorsConfigurationBuilder interface.

**Comment by tomkuijsten** [comment]
I like the fluent configuration for cors.

The one thing I'm not sure of is if EnableCors should be a direct member of the HttpServer. What if we introduce another configuration option tomorrow, will the HttpServer be the place to add it? I would suggest to accept a e.g. HttpConfiguration in the Start method. This will be the place to configure things like cors, authentication, port etc.

```cs
var serverConfiguration = new HttpConfiguration() 
  {
    Port = 8800,
    EnableSSL = true
  });  
  
serverConfiguration.EnableCors(x => x
  .AddAllowedOrigin("http://server1.com")
  .AddAllowedOrigin("http://server2.com"));  
  
server.StartAsync(serverConfiguration);
```

What do you think?

**Comment by Jark** [comment]
Hi @tomkuijsten, 

I've added the proposed solution in: https://github.com/Jark/restup/commit/4b507e4a44cf8736e4e1e2c4674201abbf6dbdeb

Ideally we'd move the RegisterRoute methods into the configuration as well, but couldn't see how to do that unless I break the interface of the httpServer...

Also, what do you think of the following pattern:

```
var configuration = HttpServerConfigurationFactory.Create()
                                    .ListenOnPort(80)
                                    .RegisterRoute("/api", new RestRouteHandler())
                                    .EnableCors()
                                    .Build();
```
The configuration returned would be a `HttpServerConfiguration`, which will have an internal constructor so we can always add stuff without having to add more constructors. Plus it has the advantage of being immutable.

The returned type of the `HttpServerConfigurationFactory.Create()` method would be a `IHttpServerConfigurationBuilder`, which on calling the Build() method would return a instantiated `HttpServerConfiguration`.

Let me know what you think of this idea, I really like having the configuration separate from the HttpServer itself.

**Comment by tomkuijsten** [comment]
Looked at your proposed solution, looks good.

I'm not that into fluent API's, but it sure looks intuitive. The only downside to this approach would be the "out-of-the-box" experience. With the current implementation you know a bit more what to do when you installed the nuget package. You see a ``` HttpServer``` class and the constructor takes a ``` int port ```, easy as .... It's not that obvious what you should do if you have a constructor that accepts a ```HttpServerConfiguration``` but that type doesn't have an accessible constructor and no static create methods. Do you follow? Would be nice if the code itself would point you in the right direction.

What's the downside of adding the ```HttpServerConfigurationFactory.Create()``` to the ```HttpServerConfiguration``` (which can still be an immutable ofcourse).

**Comment by tomkuijsten** [comment]
Any idea when you can continue on this feature? If you have limited time, tell me, we could merge the current state and I will finish up the remaining issues.

**Comment by Jark** [comment]
Sorry I thought I replied but didn't! I can fudge something together in my break (so in about 2 hours). Shouldn't take too long :) Is that ok? We can merge that back then.

**Comment by tomkuijsten** [comment]
I am away this weekend, so no rushing needed 😀. See what you can do, lets try to merge on monday. I have some time next week to finish up the feature.

**Comment by Jark** [comment]
I've modified the fluent configuration to match the new design, I did do it without the Create() method, take a look :)

**Comment by tomkuijsten** [comment]
Big thanks for you @Jark

**Comment by micharichter** [comment]
Hi, ist the CORS feature useable now, or should I be a little bit more patient ?

**Comment by tomkuijsten** [comment]
A liiiiiitle bit more patient, please. Wrapping things up, rc release is imminent :)

**Comment by micharichter** [comment]
Hi, 
oki doki :-) . Thanks for your comment....and for your work also !

**Pull request merged**
